### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by sinplosion** [ilarijn/recipebase#6]
Ladattu: 2019-11-26 19:57:30

Katselmonnissa testattu kirjautumista, käyttäjän luontia, reseptin luontia, reseptien listausta, hakua, ainesosien luontia ja ainesosien listaamista. Ohjelmassa ei tullut vastaan yhtään Server Erroreita.

Validointi koodissa toimii hyvin lukuunottamatta IngredientFormin kcal, joka voi olla negatiivinen arvo. [validators.NumberRange(min=1, max=None)] lisääminen korjasi asian.

Hakiessa on käytössä LIKE, mutta sen lisäksi voisi myös olla LOWER, jotta esim hakusanalla riisi löytyisi Riisi. Saman voisi tehdä hakusanalle.

Ainesosissa voisi jotenkin tarkistella duplicaatteja. Reseptejä luodessa on hyvin toimittu ainesosien kanssa listamalla olemassaolevia dropdown menulla, mutta tässäkin tilanteessa tulokset erottavat isot ja pienet kirjaimet. Jonkinlainen funktio joka tarkistelisi tietokantaa nimen mukaan tai nimen ja yksikön mukaan helpottaisi tuplakappaleiden erottelua, niin ingredients tauluun ei tulisi täsmälleen yhtenäisiä rivejä id:tä lukuunottamatta.  

Pieni ongelma ainesosien kanssa on myös ettei niitä voi poistaa selaimen kautta ollenkaan, joka on ymmärrettävää tilanteissa jossa ainesosa on reseptin käytössä, mutta delete napin voisi lisätä, joka tarkistelee id:n mukaan onko ingredient kiinni missään recipessä.

Rakenteeltaan koodi on selvää ja ymmärrettävää, ja ohjelma toimii selkästi ja toivotusti. Listatut ongelmat ovat vähäisiä ja eivät vaikuta ohjelman toimintaan suuresti.

**Comment by ilarijn** [comment]
Kiitos palautteesta! Vinkit ja huomiot auttoivat jo eteenpäin hakutoiminnon parantamisessa.
